In [1]:
import numpy as np
print (dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'Bytes0', 'CLIP', 'ComplexWarning', 'DataSource', 'Datetime64', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Str0', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'Uint64', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spe

In [4]:
arr1 = np.array ([21,22, 23, 24]) #one dimension array
arr1

array([21, 22, 23, 24])

In [5]:
arr1.dtype

dtype('int32')

In [6]:
arr1.ndim

1

In [7]:
arr1.shape

(4,)

In [9]:
arr2 = np.array ([[21,22, 23, 24], [25, 26, 27, 28]]) #two dimension array(matrix)
arr2

array([[21, 22, 23, 24],
       [25, 26, 27, 28]])

In [11]:
arr2 = np.array ([[21,22, 23, 24], [25, 26, 27, 28]], dtype = 'int32') #changing the integer data type, bcos the higher the number, the lesser the storage space on python 
arr2
arr2.dtype

dtype('int32')

In [13]:
np.ones(15) #on default, it is float

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
np.ones(15, dtype=int) #unless otherwise changed 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [15]:
np.zeros(15)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.linspace(15,100) #default is 50 output


array([ 15.        ,  16.73469388,  18.46938776,  20.20408163,
        21.93877551,  23.67346939,  25.40816327,  27.14285714,
        28.87755102,  30.6122449 ,  32.34693878,  34.08163265,
        35.81632653,  37.55102041,  39.28571429,  41.02040816,
        42.75510204,  44.48979592,  46.2244898 ,  47.95918367,
        49.69387755,  51.42857143,  53.16326531,  54.89795918,
        56.63265306,  58.36734694,  60.10204082,  61.83673469,
        63.57142857,  65.30612245,  67.04081633,  68.7755102 ,
        70.51020408,  72.24489796,  73.97959184,  75.71428571,
        77.44897959,  79.18367347,  80.91836735,  82.65306122,
        84.3877551 ,  86.12244898,  87.85714286,  89.59183673,
        91.32653061,  93.06122449,  94.79591837,  96.53061224,
        98.26530612, 100.        ])

In [17]:
np.linspace(15,100,15) #default is 50 output, but you can specify. that is the reason for the other 15

array([ 15.        ,  21.07142857,  27.14285714,  33.21428571,
        39.28571429,  45.35714286,  51.42857143,  57.5       ,
        63.57142857,  69.64285714,  75.71428571,  81.78571429,
        87.85714286,  93.92857143, 100.        ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
arr3 = np.arange(1,101)
arr3

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [21]:
arr3 = np.arange(1,101,3)
arr3

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [22]:
#orrrr
arr3 = np.arange(1,101, step=3)
arr3

array([  1,   4,   7,  10,  13,  16,  19,  22,  25,  28,  31,  34,  37,
        40,  43,  46,  49,  52,  55,  58,  61,  64,  67,  70,  73,  76,
        79,  82,  85,  88,  91,  94,  97, 100])

In [24]:
arr4 = np.random.randint(14,85)
arr4

38

In [25]:
arr4 = np.random.randint(14,85, size = 100)
arr4

array([54, 67, 28, 14, 39, 46, 66, 69, 38, 30, 58, 57, 31, 57, 80, 52, 39,
       14, 67, 80, 81, 76, 28, 59, 38, 81, 35, 67, 44, 26, 51, 79, 61, 45,
       70, 46, 61, 81, 81, 41, 77, 78, 27, 24, 33, 44, 57, 81, 23, 63, 27,
       33, 38, 36, 39, 25, 23, 30, 54, 30, 47, 26, 21, 33, 53, 70, 35, 79,
       84, 71, 79, 50, 51, 35, 15, 24, 34, 30, 38, 57, 49, 71, 18, 55, 68,
       65, 73, 16, 46, 60, 84, 14, 71, 77, 69, 69, 28, 58, 17, 58])

In [26]:
np.random.seed(1)
arr4 = np.random.randint(14,85, size =100)
arr4

array([51, 26, 23, 19, 78, 30, 15, 20, 39, 64, 34, 32, 25, 42, 43, 28, 64,
       82, 27, 23, 21, 77, 75, 36, 71, 15, 14, 74, 22, 27, 61, 44, 17, 84,
       35, 63, 71, 17, 82, 38, 57, 40, 66, 55, 29, 78, 82, 39, 21, 40, 39,
       36, 23, 81, 37, 41, 51, 71, 52, 22, 46, 48, 24, 37, 29, 39, 76, 60,
       46, 37, 69, 79, 17, 14, 20, 66, 84, 16, 35, 21, 57, 34, 44, 50, 21,
       59, 82, 71, 27, 24, 37, 21, 38, 34, 46, 26, 79, 74, 38, 16])

In [27]:
arr4 = arr4.reshape(10,10)
arr4

array([[51, 26, 23, 19, 78, 30, 15, 20, 39, 64],
       [34, 32, 25, 42, 43, 28, 64, 82, 27, 23],
       [21, 77, 75, 36, 71, 15, 14, 74, 22, 27],
       [61, 44, 17, 84, 35, 63, 71, 17, 82, 38],
       [57, 40, 66, 55, 29, 78, 82, 39, 21, 40],
       [39, 36, 23, 81, 37, 41, 51, 71, 52, 22],
       [46, 48, 24, 37, 29, 39, 76, 60, 46, 37],
       [69, 79, 17, 14, 20, 66, 84, 16, 35, 21],
       [57, 34, 44, 50, 21, 59, 82, 71, 27, 24],
       [37, 21, 38, 34, 46, 26, 79, 74, 38, 16]])

In [28]:
arr4[4,5] 
#anytime you have to pick a particular value, you have to go thru the location on the row and on the column

78

In [29]:
#selecting chunk of values, don't forget that the rules of range applies
arr4[3:8, 3:7]

array([[84, 35, 63, 71],
       [55, 29, 78, 82],
       [81, 37, 41, 51],
       [37, 29, 39, 76],
       [14, 20, 66, 84]])

In [31]:
#broadcasting
arr4[3:8, 3:7] = 50
arr4

array([[51, 26, 23, 19, 78, 30, 15, 20, 39, 64],
       [34, 32, 25, 42, 43, 28, 64, 82, 27, 23],
       [21, 77, 75, 36, 71, 15, 14, 74, 22, 27],
       [61, 44, 17, 50, 50, 50, 50, 17, 82, 38],
       [57, 40, 66, 50, 50, 50, 50, 39, 21, 40],
       [39, 36, 23, 50, 50, 50, 50, 71, 52, 22],
       [46, 48, 24, 50, 50, 50, 50, 60, 46, 37],
       [69, 79, 17, 50, 50, 50, 50, 16, 35, 21],
       [57, 34, 44, 50, 21, 59, 82, 71, 27, 24],
       [37, 21, 38, 34, 46, 26, 79, 74, 38, 16]])

In [32]:
arr4 = arr4.flatten()
arr4

array([51, 26, 23, 19, 78, 30, 15, 20, 39, 64, 34, 32, 25, 42, 43, 28, 64,
       82, 27, 23, 21, 77, 75, 36, 71, 15, 14, 74, 22, 27, 61, 44, 17, 50,
       50, 50, 50, 17, 82, 38, 57, 40, 66, 50, 50, 50, 50, 39, 21, 40, 39,
       36, 23, 50, 50, 50, 50, 71, 52, 22, 46, 48, 24, 50, 50, 50, 50, 60,
       46, 37, 69, 79, 17, 50, 50, 50, 50, 16, 35, 21, 57, 34, 44, 50, 21,
       59, 82, 71, 27, 24, 37, 21, 38, 34, 46, 26, 79, 74, 38, 16])

In [34]:
np.sum(arr4)

4338

In [35]:
np.mean(arr4)

43.38

In [36]:
np.median(arr4)

44.0

In [37]:
np.max(arr4)

82

In [38]:
np.min(arr4)

14

In [40]:
np.percentile(arr4,50)

44.0

In [41]:
np.quantile(arr4,0.5)

44.0

In [42]:
np.sqrt(arr4)

array([7.14142843, 5.09901951, 4.79583152, 4.35889894, 8.83176087,
       5.47722558, 3.87298335, 4.47213595, 6.244998  , 8.        ,
       5.83095189, 5.65685425, 5.        , 6.4807407 , 6.55743852,
       5.29150262, 8.        , 9.05538514, 5.19615242, 4.79583152,
       4.58257569, 8.77496439, 8.66025404, 6.        , 8.42614977,
       3.87298335, 3.74165739, 8.60232527, 4.69041576, 5.19615242,
       7.81024968, 6.63324958, 4.12310563, 7.07106781, 7.07106781,
       7.07106781, 7.07106781, 4.12310563, 9.05538514, 6.164414  ,
       7.54983444, 6.32455532, 8.1240384 , 7.07106781, 7.07106781,
       7.07106781, 7.07106781, 6.244998  , 4.58257569, 6.32455532,
       6.244998  , 6.        , 4.79583152, 7.07106781, 7.07106781,
       7.07106781, 7.07106781, 8.42614977, 7.21110255, 4.69041576,
       6.78232998, 6.92820323, 4.89897949, 7.07106781, 7.07106781,
       7.07106781, 7.07106781, 7.74596669, 6.78232998, 6.08276253,
       8.30662386, 8.88819442, 4.12310563, 7.07106781, 7.07106

In [43]:
np.sin(arr4)

array([ 0.67022918,  0.76255845, -0.8462204 ,  0.14987721,  0.51397846,
       -0.98803162,  0.65028784,  0.91294525,  0.96379539,  0.92002604,
        0.52908269,  0.55142668, -0.13235175, -0.91652155, -0.83177474,
        0.27090579,  0.92002604,  0.31322878,  0.95637593, -0.8462204 ,
        0.83665564,  0.99952016, -0.38778164, -0.99177885,  0.95105465,
        0.65028784,  0.99060736, -0.98514626, -0.00885131,  0.95637593,
       -0.96611777,  0.01770193, -0.96139749, -0.26237485, -0.26237485,
       -0.26237485, -0.26237485, -0.96139749,  0.31322878,  0.29636858,
        0.43616476,  0.74511316, -0.02655115, -0.26237485, -0.26237485,
       -0.26237485, -0.26237485,  0.96379539,  0.83665564,  0.74511316,
        0.96379539, -0.99177885, -0.8462204 , -0.26237485, -0.26237485,
       -0.26237485, -0.26237485,  0.95105465,  0.98662759, -0.00885131,
        0.90178835, -0.76825466, -0.90557836, -0.26237485, -0.26237485,
       -0.26237485, -0.26237485, -0.30481062,  0.90178835, -0.64

In [44]:
np.cos(arr4)

array([ 0.7421542 ,  0.64691932, -0.53283302,  0.98870462, -0.85780309,
        0.15425145, -0.75968791,  0.40808206,  0.26664293,  0.39185723,
       -0.84857027,  0.83422336,  0.99120281, -0.39998531,  0.5551133 ,
       -0.96260587,  0.39185723,  0.9496777 , -0.29213881, -0.53283302,
       -0.54772926, -0.03097503,  0.92175127, -0.12796369, -0.30902273,
       -0.75968791,  0.13673722,  0.17171734, -0.99996083, -0.29213881,
       -0.25810164,  0.99984331, -0.27516334,  0.96496603,  0.96496603,
        0.96496603,  0.96496603, -0.27516334,  0.9496777 ,  0.95507364,
        0.89986683, -0.66693806, -0.99964746,  0.96496603,  0.96496603,
        0.96496603,  0.96496603,  0.26664293, -0.54772926, -0.66693806,
        0.26664293, -0.12796369, -0.53283302,  0.96496603,  0.96496603,
        0.96496603,  0.96496603, -0.30902273, -0.16299078, -0.99996083,
       -0.43217794, -0.64014434,  0.42417901,  0.96496603,  0.96496603,
        0.96496603,  0.96496603, -0.95241298, -0.43217794,  0.76

In [45]:
np.tan(arr4)

array([ 9.03086149e-01,  1.17875355e+00,  1.58815308e+00,  1.51589471e-01,
       -5.99179998e-01, -6.40533120e+00, -8.55993401e-01,  2.23716094e+00,
        3.61455441e+00,  2.34786031e+00, -6.23498963e-01,  6.61006041e-01,
       -1.33526407e-01,  2.29138799e+00, -1.49838734e+00, -2.81429605e-01,
        2.34786031e+00,  3.29826407e-01, -3.27370380e+00,  1.58815308e+00,
       -1.52749853e+00, -3.22685758e+01, -4.20700951e-01,  7.75047091e+00,
       -3.07762040e+00, -8.55993401e-01,  7.24460662e+00, -5.73702254e+00,
        8.85165604e-03, -3.27370380e+00,  3.74316794e+00,  1.77046993e-02,
        3.49391565e+00, -2.71900612e-01, -2.71900612e-01, -2.71900612e-01,
       -2.71900612e-01,  3.49391565e+00,  3.29826407e-01,  3.10309661e-01,
        4.84699227e-01, -1.11721493e+00,  2.65605178e-02, -2.71900612e-01,
       -2.71900612e-01, -2.71900612e-01, -2.71900612e-01,  3.61455441e+00,
       -1.52749853e+00, -1.11721493e+00,  3.61455441e+00,  7.75047091e+00,
        1.58815308e+00, -

In [46]:
np.log(arr4)

array([3.93182563, 3.25809654, 3.13549422, 2.94443898, 4.35670883,
       3.40119738, 2.7080502 , 2.99573227, 3.66356165, 4.15888308,
       3.52636052, 3.4657359 , 3.21887582, 3.73766962, 3.76120012,
       3.33220451, 4.15888308, 4.40671925, 3.29583687, 3.13549422,
       3.04452244, 4.34380542, 4.31748811, 3.58351894, 4.26267988,
       2.7080502 , 2.63905733, 4.30406509, 3.09104245, 3.29583687,
       4.11087386, 3.78418963, 2.83321334, 3.91202301, 3.91202301,
       3.91202301, 3.91202301, 2.83321334, 4.40671925, 3.63758616,
       4.04305127, 3.68887945, 4.18965474, 3.91202301, 3.91202301,
       3.91202301, 3.91202301, 3.66356165, 3.04452244, 3.68887945,
       3.66356165, 3.58351894, 3.13549422, 3.91202301, 3.91202301,
       3.91202301, 3.91202301, 4.26267988, 3.95124372, 3.09104245,
       3.8286414 , 3.87120101, 3.17805383, 3.91202301, 3.91202301,
       3.91202301, 3.91202301, 4.09434456, 3.8286414 , 3.61091791,
       4.2341065 , 4.36944785, 2.83321334, 3.91202301, 3.91202

In [47]:
np.var(arr4)

344.23560000000003

In [48]:
np.std(arr4)

18.553587254221217

In [49]:
np.floor(arr4)

array([51., 26., 23., 19., 78., 30., 15., 20., 39., 64., 34., 32., 25.,
       42., 43., 28., 64., 82., 27., 23., 21., 77., 75., 36., 71., 15.,
       14., 74., 22., 27., 61., 44., 17., 50., 50., 50., 50., 17., 82.,
       38., 57., 40., 66., 50., 50., 50., 50., 39., 21., 40., 39., 36.,
       23., 50., 50., 50., 50., 71., 52., 22., 46., 48., 24., 50., 50.,
       50., 50., 60., 46., 37., 69., 79., 17., 50., 50., 50., 50., 16.,
       35., 21., 57., 34., 44., 50., 21., 59., 82., 71., 27., 24., 37.,
       21., 38., 34., 46., 26., 79., 74., 38., 16.])

In [50]:
#EXERCISE
arr5 = np.random.randint(15,75, size = 150)
arr5

array([59, 43, 54, 49, 25, 69, 47, 56, 33, 37, 21, 17, 22, 54, 63, 69, 30,
       20, 32, 57, 35, 69, 63, 37, 52, 28, 64, 65, 48, 68, 35, 25, 47, 70,
       71, 40, 36, 54, 47, 72, 34, 40, 64, 29, 28, 35, 67, 58, 21, 28, 71,
       74, 30, 39, 74, 24, 17, 22, 68, 20, 51, 52, 71, 36, 55, 28, 42, 64,
       64, 62, 28, 55, 29, 60, 38, 31, 43, 57, 60, 18, 67, 17, 29, 61, 15,
       44, 26, 50, 68, 44, 48, 17, 35, 34, 63, 69, 47, 43, 70, 33, 46, 43,
       45, 25, 23, 60, 50, 47, 23, 35, 28, 65, 30, 56, 15, 59, 34, 39, 64,
       57, 35, 59, 30, 45, 42, 29, 66, 34, 74, 41, 58, 37, 22, 50, 68, 62,
       61, 66, 49, 51, 51, 47, 34, 18, 39, 34, 52, 45, 53, 62])

In [52]:
arr5 = arr5.reshape(15, 10)
arr5

array([[59, 43, 54, 49, 25, 69, 47, 56, 33, 37],
       [21, 17, 22, 54, 63, 69, 30, 20, 32, 57],
       [35, 69, 63, 37, 52, 28, 64, 65, 48, 68],
       [35, 25, 47, 70, 71, 40, 36, 54, 47, 72],
       [34, 40, 64, 29, 28, 35, 67, 58, 21, 28],
       [71, 74, 30, 39, 74, 24, 17, 22, 68, 20],
       [51, 52, 71, 36, 55, 28, 42, 64, 64, 62],
       [28, 55, 29, 60, 38, 31, 43, 57, 60, 18],
       [67, 17, 29, 61, 15, 44, 26, 50, 68, 44],
       [48, 17, 35, 34, 63, 69, 47, 43, 70, 33],
       [46, 43, 45, 25, 23, 60, 50, 47, 23, 35],
       [28, 65, 30, 56, 15, 59, 34, 39, 64, 57],
       [35, 59, 30, 45, 42, 29, 66, 34, 74, 41],
       [58, 37, 22, 50, 68, 62, 61, 66, 49, 51],
       [51, 47, 34, 18, 39, 34, 52, 45, 53, 62]])

In [55]:
arr5[5:9, 4:9] 

array([[74, 24, 17, 22, 68],
       [55, 28, 42, 64, 64],
       [38, 31, 43, 57, 60],
       [15, 44, 26, 50, 68]])

In [57]:
arr5[5:9, 4:9] = 45
arr5

array([[59, 43, 54, 49, 25, 69, 47, 56, 33, 37],
       [21, 17, 22, 54, 63, 69, 30, 20, 32, 57],
       [35, 69, 63, 37, 52, 28, 64, 65, 48, 68],
       [35, 25, 47, 70, 71, 40, 36, 54, 47, 72],
       [34, 40, 64, 29, 28, 35, 67, 58, 21, 28],
       [71, 74, 30, 39, 45, 45, 45, 45, 45, 20],
       [51, 52, 71, 36, 45, 45, 45, 45, 45, 62],
       [28, 55, 29, 60, 45, 45, 45, 45, 45, 18],
       [67, 17, 29, 61, 45, 45, 45, 45, 45, 44],
       [48, 17, 35, 34, 63, 69, 47, 43, 70, 33],
       [46, 43, 45, 25, 23, 60, 50, 47, 23, 35],
       [28, 65, 30, 56, 15, 59, 34, 39, 64, 57],
       [35, 59, 30, 45, 42, 29, 66, 34, 74, 41],
       [58, 37, 22, 50, 68, 62, 61, 66, 49, 51],
       [51, 47, 34, 18, 39, 34, 52, 45, 53, 62]])

In [58]:
np.sum(arr5)

6818

In [59]:
np.mean(arr5)

45.45333333333333

In [60]:
np.median(arr5)

45.0

In [61]:
np.argmax(arr5) #location of the max value

51

In [62]:
np.argmin(arr5) #location of the min value

114

In [63]:
np.percentile(arr5, 25)

34.0

In [64]:
np.percentile(arr5, 50)

45.0

In [65]:
np.std(arr5)

15.01935935902579

In [66]:
np.var(arr5)

225.5811555555556